name=LC_DFRobot_0669
version=1.0
author=jim lee
maintainer=DFRobot_0669@leftcoast.biz
sentence=A set of tools to allow the DFRobot 0669 to run the left coast GUI.
paragraph=This is a set of tools for doing.. Well, what they said above.
category=Uncategorized
url=https://github.com/leftCoast/LC_DFRobot_0669
architectures=*
depends=LC_baseTools,LC_SPI,LC_GUITools,Adafruit_GFX
dot_a_linkage=true
